// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6rue5UTv9R4CaZ8bmWcL7QmmXHiuG5Eo',
    appId: '1:708083984008:web:a8e4f6168d7f50a632213d',
    messagingSenderId: '708083984008',
    projectId: 'flutterfarkle',
    authDomain: 'flutterfarkle.firebaseapp.com',
    storageBucket: 'flutterfarkle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3RC7Qfzrz_-lqvQYI5yVsZDQORfNyGGo',
    appId: '1:708083984008:android:b145038befcd30fc32213d',
    messagingSenderId: '708083984008',
    projectId: 'flutterfarkle',
    storageBucket: 'flutterfarkle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoSbTRlvd5Je5Au-S5YqtPctTbfhW7F_8',
    appId: '1:708083984008:ios:45138e0992da077c32213d',
    messagingSenderId: '708083984008',
    projectId: 'flutterfarkle',
    storageBucket: 'flutterfarkle.appspot.com',
    iosClientId: '708083984008-ll5qklc9ijuvehavn117portvbkq9gph.apps.googleusercontent.com',
    iosBundleId: 'dev.sustare.flutterfarkle',
  );
}
